# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d80f554a18f97012ceb7eb134825101dce43e576bd2ab65b439bbc349b7cf72fb47a2c874ef648dcd1c085b28fe84d9a403436a7efaea06e482fce6660131b24

test:
  secret_key_base: d050e834cc857d2cd338eabe7af655e390c2e2a177ef929127a05302582d9e5d23b310d9785f4746851505589bcb3060f4553d82fde6365039df1005ee13c8aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
